version: '3.9'

services:
    node:
        build:
            context:
                ./
        depends_on:
            - postgres
        ports:
            - "8086:80"
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: hunter2
            POSTGRES_DB: sfn
        ports:
            - "5433:5432"